# Site settings
title: Superloop documentation
email: ljbha007@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://superloopd.github.io" # the base hostname & protocol for your site
github_username:  carllee

# Build settings
markdown: kramdown
